version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /work/jsy/Unified_Log_Analytics_Platform/docker_compose/prometheus_grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - "--storage.tsdb.retention.time=3d"
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
