filebeat.config.inputs:
  enabled: true
  path: '/etc/filebeat/inputs/*.yml'
  reload.enabled: true

# Kafka 출력 설정
output.kafka:
  hosts: ["192.168.122.60:9092", "192.168.122.61:9092", "192.168.122.62:9092"]
  topic: '%{[kafka_topic]}'
  required_acks: 1
  codec.format:
     string: '%{[@timestamp]} %{[host.name]} %{[message]}'


# 로컬 파일로 저장 설정
#output.file:
#  path: "/etc/filebeat"
#  filename: "test.log"
#  permissions: 0644
#  codec.format:
#    string: '%{[@timestamp]} %{[host.name]} %{[message]}'

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 3
  permissions: 0644
logging.to_syslog: false
logging.to_journal: false
